# Generated by Django 4.0.6 on 2023-06-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
