# Generated by Django 4.0.6 on 2023-06-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_profile_firstname_remove_profile_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
