# Generated by Django 4.0.6 on 2023-06-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_profile_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catefory',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
